### ISSUE TITLE
Target of URI doesn't exist: 'package:open_file_manager/open_file_manager.dart'.

### ISSUE THREAD

**Issue by robertnicjoo** [nayanAubie/open_file_manager#4]
![0011](https://github.com/nayanAubie/open_file_manager/assets/8672823/b07b24c7-17dd-41d8-9a98-cdb17f46820e)

**Comment by nayanaubie** [comment]
This is an issue with your system caching. you can call the `flutter clean` and `flutter pub get`. still, you are facing the issue then you can delete the folder: `<username>/pub.cache/hosted/pub.dev` and try `flutter pub get`
